### ISSUE TITLE
"Uncaught ReferenceError: regeneratorRuntime is not defined" in jspsych 7.2.2 with CDN method

### ISSUE THREAD

**Issue by ZhaoBin-Li** [jspsych/jsPsych#2642]
Hi jsPsych, 

I really appreciate jspsych in helping to code my experiments online. For release 7.2.2, there is a bug with plugins like image-button-response with the CDN method. For instance, the [image-button-response demo](https://www.jspsych.org/7.2/demos/jspsych-image-button-response-demo1.html) gives the error in chrome console: 

```
jspsych@7.2.2:1 Uncaught ReferenceError: regeneratorRuntime is not defined
    at r.value (jspsych@7.2.2:1:61308)
    at jspsych-image-button-response-demo1.html:32:15
```

The error does not appear when I am hosting jspsych 7.2.2 or with 7.2.1. Thank you for your consideration.

Regards,
ZhaoBin

**Comment by bjoluc** [comment]
Hi @ZhaoBin-Li,

thanks for reporting this! It's related to the Babel build relying on `regeneratorRuntime`, which is currently not in any `index.brwoser.min.js` build artifact. I think the best fix here is to add `regeneratorRuntime` to the `jspsych` `index.brwoser.min.js` build. Looking into this now.

**Comment by bjoluc** [comment]
@ZhaoBin-Li We just released `jspsych@7.2.3` which fixes this. Thanks again!

**Comment by becky-gilbert** [comment]
Hi all, I know this issue is closed but I'm still getting the `regeneratorRuntime` error with `jspsych@7.2.3` and up when loading via unpkg. Here's how I'm loading scripts:
```html
    <head>
        <title>Experiment</title>
        <!-- More recent versions give me the same error, but 7.2.1 works -->
        <script src="https://unpkg.com/jspsych@7.2.3"></script>
        <script src="https://unpkg.com/@jspsych/plugin-html-button-response@1.1.2"></script>
        <script src="../dist/index.browser.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/jspsych@7.3.0/css/jspsych.css" type="text/css"/>
    </head>
```
and here's the error:
![Screen Shot 2022-10-28 at 12 10 21 PM](https://user-images.githubusercontent.com/9041788/198721165-373dcd7e-a1b5-4d32-89f5-05ef949e1e6e.png)
In case it's relevant: I'm working on a new plugin using the jspsych-contrib typescript template, which is what I'm loading via `../dist/index.browser.js`.
I know @bjoluc said this was fixed in v7.2.3 so I must be doing something silly...

**Comment by bjoluc** [comment]
Hi @becky-gilbert, I'm unable to reproduce this – can you provide a repro repo?
